# Generated by Django 3.2.7 on 2021-11-26 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idRegister', models.AutoField(primary_key=True, serialize=False, verbose_name='idRegister')),
                ('name_company', models.CharField(max_length=50, verbose_name='Name_company')),
                ('name_contact', models.CharField(max_length=50, verbose_name='Name_contact')),
                ('cel', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(max_length=80, verbose_name='Address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='Email')),
            ],
        ),
    ]
