# Generated by Django 3.2.7 on 2021-11-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedoresApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='name_company',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name_company'),
        ),
    ]
