# Generated by Django 3.2.7 on 2021-12-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedoresApp', '0002_alter_proveedor_name_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='name_company',
            field=models.CharField(max_length=50, verbose_name='Name_company'),
        ),
    ]
