# Generated by Django 3.2.7 on 2021-11-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='', max_length=30, verbose_name='Lastname'),
        ),
    ]
