# Generated by Django 3.2.7 on 2021-11-24 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('categories', models.CharField(choices=[('S', 'Ciclismo'), ('T', 'Atletismo'), ('F', 'Boxeo'), ('D', 'Futbol'), ('S', 'Voleibol'), ('T', 'Baloncesto'), ('F', 'Natacion'), ('D', 'Tenis')], max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('user', models.CharField(max_length=30, verbose_name='User')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=30, verbose_name='Company')),
                ('contact_name', models.CharField(max_length=50, verbose_name='Contact name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('city', models.CharField(choices=[('Barranquilla', 'Barranquilla'), ('Bogotá', 'Bogotá'), ('Cali', 'Cali'), ('Manizales', 'Manizales'), ('Medellín', 'Medellín')], max_length=20, verbose_name='City')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('Shipping_id', models.AutoField(primary_key=True, serialize=False)),
                ('conveyor', models.CharField(choices=[('S', 'Servientrega'), ('T', 'TCC'), ('F', 'Fedex'), ('D', 'DHL')], max_length=64)),
                ('delivery_time', models.DateTimeField()),
                ('was_delivered', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('C', 'Credito'), ('D', 'Debito'), ('P', 'paypal'), ('N', 'Nequi')], max_length=64)),
                ('shipping_address', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Customer_Order', to='authApp.customer')),
                ('shipping_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Shipping_Order', to='authApp.shipping')),
            ],
        ),
    ]
