# Generated by Django 3.2.7 on 2021-12-04 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Type Name')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_products', models.IntegerField(primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.type')),
            ],
        ),
    ]
